services:
  short_relation_service:
    build: .
    container_name: token-service-3
    ports:
      - "1342:5000"
    environment:
      FLAG: "CCCTF{f100R_5Um_g0TT4_b3_usefaahhh}"
    restart: unless-stopped
